{
  "swagger" : "2.0",
  "x-ing-guidelines-version" : 1,
  "info" : {
    "title" : "Showcase API",
    "description" : "The API shows the Open Banking Platform in operation through its endpoint. It is available on the marketplace to subscribe to, and it is accessible to internal and external applications. The '/greetings/single' endpoint shows the functionality of the platform in action.",
    "version" : "2.0.3",
    "contact" : {
      "name" : "ING Developer Portal",
      "url" : "https://developer.ing.com",
      "email" : "developerportal@ing.com"
    }
  },
  "host" : "api.ing.com",
  "basePath" : "/",
  "securityDefinitions" : {
    "ING-Application-Security" : {
      "type" : "oauth2",
      "flow" : "application",
      "tokenUrl" : "https://api.ing.com/oauth2/token",
      "scopes" : {
        "greetings:view" : "Get greetings messages."
      }
    }
  },
  "schemes" : [ "https" ],
  "consumes" : [ "application/json" ],
  "produces" : [ "application/json" ],
  "paths" : {
    "/greetings/single" : {
      "get" : {
        "summary" : "Gives a greeting message from one of the available instances",
        "description" : "Returns a message generated with a unique id and a timestamp indicating when it was produced.",
        "tags" : [ "greetings" ],
        "security" : [ {
          "ING-Application-Security" : [ "greetings:view" ]
        } ],
        "parameters" : [ {
          "$ref" : "#/parameters/AuthorizationBearerInHeader"
        }, {
          "$ref" : "#/parameters/SignatureInHeader"
        }, {
          "$ref" : "#/parameters/DigestInHeader"
        }, {
          "$ref" : "#/parameters/DateInHeader"
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "schema" : {
              "$ref" : "#/definitions/Greeting"
            },
            "headers" : {
              "X-ING-ReqID" : {
                "type" : "string",
                "description" : "Request ID, can be a UUID"
              },
              "X-ING-Response-ID" : {
                "type" : "string",
                "description" : "Response UUID, if X-ING-ReqID supplied in the request"
              },
              "Signature" : {
                "type" : "string",
                "description" : "A signature of the response based on X-ING-ReqID and X-ING-Response-ID. This header is deprecated"
              }
            }
          },
          "400" : {
            "$ref" : "#/responses/BadRequest"
          },
          "401" : {
            "$ref" : "#/responses/Unauthorized"
          },
          "404" : {
            "$ref" : "#/responses/NotFound"
          },
          "500" : {
            "$ref" : "#/responses/InternalServerError"
          },
          "503" : {
            "$ref" : "#/responses/ServiceUnavailable"
          }
        }
      }
    }
  },
  "definitions" : {
    "Greeting" : {
      "type" : "object",
      "required" : [ "message", "id", "messageTimestamp" ],
      "properties" : {
        "message" : {
          "type" : "string",
          "description" : "A greeting message",
          "example" : "Welcome to ING!"
        },
        "id" : {
          "type" : "string",
          "description" : "A generated uuid",
          "example" : "aba4b176-8834-467d-9c2a-ee6acfc8fceb"
        },
        "messageTimestamp" : {
          "type" : "string",
          "description" : "The current time (GMT)",
          "example" : "2018-07-30 15:42:17 GMT"
        }
      }
    }
  },
  "responses" : {
    "BadRequest" : {
      "description" : "Bad Request - The request was malformed, headers may be missing or invalid.",
      "schema" : {
        "$ref" : "https://api.touchpoint.ing.net/schemas/error/1.0"
      },
      "examples" : {
        "application/json" : {
          "error" : {
            "code" : "DigestError",
            "message" : "Missing or invalid Digest header",
            "severity" : "ERROR"
          }
        }
      }
    },
    "Unauthorized" : {
      "description" : "Unauthorized - The request did not contain authorisation evidence. A valid subscription to the scope(s) that contain this API endpoint is required to allow the request to succeed.",
      "schema" : {
        "$ref" : "https://api.touchpoint.ing.net/schemas/error/1.0"
      },
      "examples" : {
        "application/json" : {
          "error" : {
            "code" : "Unauthorized",
            "message" : "Missing or invalid Access Token",
            "severity" : "ERROR"
          }
        }
      }
    },
    "NotFound" : {
      "description" : "Not Found - The requested resource cannot be found. Check the request URL if it matches with the endpoint described.",
      "schema" : {
        "$ref" : "https://api.touchpoint.ing.net/schemas/error/1.0"
      },
      "examples" : {
        "application/json" : {
          "error" : {
            "code" : "NotFoundError",
            "message" : "Either there is no API method associated with the URL path of the request, or the request refers to one or more resources that were not found.",
            "severity" : "ERROR"
          }
        }
      }
    },
    "MethodNotAllowed" : {
      "description" : "Method Not Allowed - The HTTP verb is not supported by the URL endpoint used in the request.",
      "schema" : {
        "$ref" : "https://api.touchpoint.ing.net/schemas/error/1.0"
      },
      "examples" : {
        "application/json" : {
          "error" : {
            "code" : "MethodNotAllowed",
            "message" : "The HTTP verb is not supported by the URL endpoint used in the request.",
            "severity" : "ERROR"
          }
        }
      }
    },
    "InternalServerError" : {
      "description" : "Internal Server Error - Something went wrong on the server, check status site and/or report the issue. There's no need to really specify this any further (other than 503 below) as the client is powerless in fixing the condition that caused the error.",
      "schema" : {
        "$ref" : "https://api.touchpoint.ing.net/schemas/error/1.0"
      },
      "examples" : {
        "application/json" : {
          "error" : {
            "code" : "InternalServerError",
            "message" : "We encountered an internal error",
            "severity" : "ERROR"
          }
        }
      }
    },
    "ServiceUnavailable" : {
      "description" : "Service Unavailable - The API is temporarily unavailable. This is the only 500 code that allows for the client to try and remedy the condition (i.e. by retrying).",
      "schema" : {
        "$ref" : "https://api.touchpoint.ing.net/schemas/error/1.0"
      },
      "examples" : {
        "application/json" : {
          "error" : {
            "code" : "ServiceInMaintenance",
            "message" : "The API is temporarily unavailable, please try again later.",
            "severity" : "ERROR"
          }
        }
      }
    }
  },
  "parameters" : {
    "AuthorizationBearerInHeader" : {
      "name" : "Authorization",
      "in" : "header",
      "type" : "string",
      "required" : true,
      "description" : "OAuth2 token"
    },
    "SignatureInHeader" : {
      "name" : "Signature",
      "in" : "header",
      "type" : "string",
      "required" : true,
      "description" : "A signature of the request by the third party on application level. See \"Get Started\" for more information on how to generate."
    },
    "DigestInHeader" : {
      "name" : "Digest",
      "in" : "header",
      "type" : "string",
      "required" : true,
      "description" : "SHA256 of the body."
    },
    "DateInHeader" : {
      "name" : "Date",
      "in" : "header",
      "type" : "string",
      "format" : "date-time",
      "required" : true,
      "description" : "Standard http header element for date and time"
    }
  }
}